paths:
  public: "public"
files:
  scripts:
    concat:
      "scripts/app.js": "app/scripts/**/*.{js,coffee}"
      "scripts/vendor.js": "vendor/**/*.{js,coffee}"
    order:
      before:
        - "vendor/jquery-1.9.1.js"
      after:
        - "vendor/underscore.js"
        - "vendor/vendor.js"
  styles:
    concat:
      "styles/app.css": "app/styles/**/[a-z]*.{css,scss,sass}"
  templates:
    copy:
      "views/": "app/views/**/*.hbs"
modules:
  wrapper: "cmd"
conventions:
  ignored: "_"
notifications: true
