paths:
  public: "public"
files:
  scripts:
    join:
      "scripts/app.js": "app/**/*.{js,coffee}"
      "scripts/vender.js": "vendor/**/*.{js,coffee}"
    order:
      before:
        - "./vendor/jquery-1.9.1.js"
      after:
        - "./vendor/underscore.js"
