paths:
  public: "public"
files:
  - scripts:
    join:
      "scripts/app.js": "app/scripts/**/*.{js,coffee}"
      "scripts/vendor.js": "vendor/**/*.{js,coffee}"
    order:
      before:
        - "vendor/jquery-1.9.1.js"
      after:
        - "vendor/underscore.js"
  - styles:
    join:
      "styles/app.css": "app/styles/**/[a-z]*.{css,scss,sass}"
    order:
      before:
      after:
modules:
  wrapper: "cmd"
notifications: true
